### PR TITLE
Support CI in Travis

### PR DESCRIPTION
**Pull request by jetmuffin**
rebase this PR after #1 merged

### CODE REVIEW

**Comment by gaocegege** [comment]
#1 Merged.

**Comment by jetmuffin** [comment]
updated

**Comment by gaocegege** [comment]
https://travis-ci.org/kubeflow-incubator/genspec

Please repush the commit to trigger travis CI.

**Comment by jetmuffin** [comment]
seems that ci failed with go version 1.8

**Comment by gaocegege** [comment]
We do not need to support 1.8 and 1.9, I think.

**Comment by jetmuffin** [comment]
my last commit didn't trigger ci, how to retrigger it?

**Comment by gaocegege** [comment]
Please try again, I think it is a bug of Travis.

**Comment by jetmuffin** [comment]
done, all checks passed~

**Comment by gaocegege** [comment]
Thanks for your awesome contribution!

**Pull request merged**
